var MDZBmodules = new Map();
MDZBmodules.set('Kennisgebieden', { naam: 'Kennisgebieden', type: 'Basismodule', bladzijden:[
{paginatype:'basistype',paginainhoud:'<h1>Kennisgebieden</h1><p>Ik gebruik de module kennisgebieden om voor allerlei kennisgebieden (&eacute;&eacute;n per pagina) kort de structuur van het betreffende gebied te verkennen. De kennisgebieden die ik hier onderscheid zijn:</p><ul> <li>Biologie</li> <li>Scheikunde</li> <li>Natuurkunde</li> <li>Veldbiologie</li> <li>Fotografie</li></ul>'},
{paginatype:'basistype',paginainhoud:'<h1>Biologie</h1><p>Binnen het kennisgebied &quot;Biologie&quot; onderscheid ik in eerste instantie een aantal kennisterreinen, zoals ik die ook in de indeling in mijn studie zelf ben tegen gekomen:</p><ul> <li>Celbiologie; hier bestaat een directe link met Biochemie, dat ik heb ondergebracht bij Scheikunde</li> <li>Botanie <ul>  <li>Indeling plantenrijk</li>  <li>Anatomie</li>  <li>Plantenfysiologie</li> </ul> </li> <li>Zo&ouml;logie <ul>  <li>Indeling dierenrijk</li>  <li>Histologie</li>  <li>Dierfysiologie</li> </ul> </li> <li>Microbiologie</li> <li>Genetica</li> <li>Ecologie</li></ul>'},
{paginatype:'basistype',paginainhoud:'<h1>Scheikunde</h1>'},
{paginatype:'basistype',paginainhoud:'<h1>Natuurkunde</h1>'},
{paginatype:'basistype',paginainhoud:'<h1>Wiskunde</h1>'},
{paginatype:'basistype',paginainhoud:'<h1>Veldbiologie</h1><p>Veldbiologie omvat voor mij alles wat ik op niveau van organismen en groepen organismen kan waarnemen in het veld (of onder binoculair/microscoop in meegebrachte samples). Ik wil daarbij enerzijd aandacht besteden aan beschrijven van soorten en systemen, determinatietabellen, waarnemings-, vang en conserveermethoden.</p><p>Voorlopig breng ik dit onder in &eacute;&eacute;n doorlopende pagina met de nodige linken (voor- en achteruit). De linken zijn:</p><p>Groepen organismen</p><ol> <li>Planten</li> <li>Dieren</li></ol>'},
{paginatype:'basistype',paginainhoud:'<h1>Fotografie</h1>'},
]});
var MDZB_Object_Data = new Map();
var organismenMap = new Map();
organismenMap.set('1',{naam:'Aalscholver',wetenschappelijke_naam:'Phalacrocorax carbo',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('2',{naam:'Alk',wetenschappelijke_naam:'Alca torda',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('3',{naam:'Appelvink',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('4',{naam:'Baardman',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('5',{naam:'Beflijster',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('6',{naam:'Bergeend',wetenschappelijke_naam:'Tadorna tadorna',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('7',{naam:'Bijeneter',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('8',{naam:'Bladkoning',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('9',{naam:'Blauwborst',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('10',{naam:'Blauwe kiekendief',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('11',{naam:'Blauwe reiger',wetenschappelijke_naam:'Ardea cinerea',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('12',{naam:'Blonderuiter',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('13',{naam:'Boerenzwaluw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('14',{naam:'Bokje',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('15',{naam:'Bontbekplevier',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('16',{naam:'Bontekraai',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('17',{naam:'Bontestrandloper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('18',{naam:'Bontevliegenvanger',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('19',{naam:'Boomklever',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('20',{naam:'Boomkruiper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('21',{naam:'Boomleeuwerik',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('22',{naam:'Boompieper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('23',{naam:'Boomvalk',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('24',{naam:'Bosrietzanger',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('25',{naam:'Bosruiter',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('26',{naam:'Bosuil',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('27',{naam:'Braamsluiper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('28',{naam:'Brandgans',wetenschappelijke_naam:'Branta leucopsis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('29',{naam:'Breedbekstrandloper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('30',{naam:'Brilduiker',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('31',{naam:'Bruinekiekendief',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('32',{naam:'Buidelmees',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('33',{naam:'Buizerd',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('34',{naam:'Casarca',wetenschappelijke_naam:'Casarca ferruginea',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('35',{naam:'Cettiszanger',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('36',{naam:'Dodaars',wetenschappelijke_naam:'Tachybaptus rufficollis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('37',{naam:'Draaihals',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('38',{naam:'Drieteenmeeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('39',{naam:'Drieteenstrandloper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('40',{naam:'Duinpieper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('41',{naam:'Dwerggans',wetenschappelijke_naam:'Anser erythropus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('42',{naam:'Dwergmeeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('43',{naam:'Dwergstern',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('44',{naam:'Eider / Eidereend',wetenschappelijke_naam:'Somateria mollissima',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('45',{naam:'Ekster',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('46',{naam:'Engelsekwikstaart',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('47',{naam:'Europesekanarie',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('48',{naam:'Fazant',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('49',{naam:'Fitis',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('50',{naam:'Flamingo',wetenschappelijke_naam:'Phoenicopterus ruber',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('51',{naam:'Fluiter',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('52',{naam:'Frater',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('53',{naam:'Fuut',wetenschappelijke_naam:'Podiceps cristatus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('54',{naam:'Gaai',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('55',{naam:'Geelgors',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('56',{naam:'Gekraagderoodstaart',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('57',{naam:'Gelekwikstaart',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('58',{naam:'Geoorde fuut',wetenschappelijke_naam:'Podiceps nigricollis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('59',{naam:'Gestreeptestrandloper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('60',{naam:'Gierzwaluw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('61',{naam:'Glanskop',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('62',{naam:'Goudhaan',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('63',{naam:'Goudplevier',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('64',{naam:'Goudvink',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('65',{naam:'Grasmus',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('66',{naam:'Graspieper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('67',{naam:'Graszanger',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('68',{naam:'Grauwefranjepoot',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('69',{naam:'Grauwe gans',wetenschappelijke_naam:'Anser anser',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('70',{naam:'Grauwegors',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('71',{naam:'Grauwekiekendief',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('72',{naam:'Grauweklauwier',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('73',{naam:'Grauwe pijlstormvogel',wetenschappelijke_naam:'Puffinus griseus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('74',{naam:'Grauwevliegenvanger',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('75',{naam:'Griel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('76',{naam:'Groenespecht',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('77',{naam:'Groenling',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('78',{naam:'Groenpootruiter',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('79',{naam:'Grotebarmsijs',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('80',{naam:'Grotebontespecht',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('81',{naam:'Grote Canadese gans',wetenschappelijke_naam:'Branta canadensis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('82',{naam:'Grotegelekwikstaart',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('83',{naam:'Grotejager',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('84',{naam:'Grotekarekiet',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('85',{naam:'Grotekruisbek',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('86',{naam:'Grotelijster',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('87',{naam:'Grotemantelmeeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('88',{naam:'Grotepieper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('89',{naam:'Grotestern',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('90',{naam:'Grotezaagbek',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('91',{naam:'Grotezeeeend',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('92',{naam:'Grote zilverreiger',wetenschappelijke_naam:'Egretta alba',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('93',{naam:'Grutto',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('94',{naam:'Havik',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('95',{naam:'Heggenmus',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('96',{naam:'Heiligeibis',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('97',{naam:'Holenduif',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('98',{naam:'Hop',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('99',{naam:'Houtduif',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('100',{naam:'Houtsnip',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('101',{naam:'Huismus',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('102',{naam:'Huiszwaluw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('103',{naam:'IJsduiker',wetenschappelijke_naam:'Gavia immer',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('104',{naam:'Ijseend',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('105',{naam:'Ijsgors',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('106',{naam:'Ijsvogel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('107',{naam:'Jan van Gent',wetenschappelijke_naam:'Sula bassana',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('108',{naam:'Kanoet',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('109',{naam:'Kauw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('110',{naam:'Keep',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('111',{naam:'Kemphaan',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('112',{naam:'Kerkuil',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('113',{naam:'Kievit',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('114',{naam:'Klapekster',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('115',{naam:'Kleinealk',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('116',{naam:'Kleinebarmsijs',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('117',{naam:'Kleinebontespecht',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('118',{naam:'Kleinejager',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('119',{naam:'Kleinekarekiet',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('120',{naam:'Kleinemantelmeeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('121',{naam:'Kleineplevier',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('122',{naam:'Kleine rietgans',wetenschappelijke_naam:'Anser brachyrhynchus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('123',{naam:'Kleinestrandloper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('124',{naam:'Kleinevliegenvanger',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('125',{naam:'Kleine zilverreiger',wetenschappelijke_naam:'Egretta garzetta',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('126',{naam:'Kleine zwaan',wetenschappelijke_naam:'Cygnus bewickii',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('127',{naam:'Kleinstejager',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('128',{naam:'Kleinstwaterhoen',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('129',{naam:'Kleinwaterhoen',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('130',{naam:'Kluut',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('131',{naam:'Kneu',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('132',{naam:'Knobbelzwaan',wetenschappelijke_naam:'Cygnus olor',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('133',{naam:'Koekoek',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('134',{naam:'Koereiger',wetenschappelijke_naam:'Ardeola ibis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('135',{naam:'Kokmeeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('136',{naam:'Kolgans',wetenschappelijke_naam:'Anser albifrons',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('137',{naam:'Koolmees',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('138',{naam:'Koperwiek',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('139',{naam:'Korhoen',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('140',{naam:'Kraanvogel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('141',{naam:'Krakeend',wetenschappelijke_naam:'Anas strepera',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('142',{naam:'Kramsvogel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('143',{naam:'Krombekstrandloper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('144',{naam:'Krooneend',wetenschappelijke_naam:'Netta rufina',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('145',{naam:'Kruisbek',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('146',{naam:'Kuifaalscholver',wetenschappelijke_naam:'Phalacrcorax aristotelis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('147',{naam:'Kuifduiker',wetenschappelijke_naam:'Podiceps auritius',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('148',{naam:'Kuifeend',wetenschappelijke_naam:'Aythya figula',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('149',{naam:'Kuifleeuwerik',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('150',{naam:'Kuifmees',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('151',{naam:'Kwak',wetenschappelijke_naam:'Nycticorax nycticorax',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('152',{naam:'Kwartel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('153',{naam:'Kwartelkoning',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('154',{naam:'Lachstern',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('155',{naam:'Lepelaar',wetenschappelijke_naam:'Platalea Leucorodia',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('156',{naam:'Mandarijneend',wetenschappelijke_naam:'Aix galericulata',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('157',{naam:'Matkop',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('158',{naam:'Meerkoet',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('159',{naam:'Merel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('160',{naam:'Middelstebontespecht',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('161',{naam:'Middelstejager',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('162',{naam:'Middelstezaagbek',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('163',{naam:'Morinelplevier',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('164',{naam:'Nachtegaal',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('165',{naam:'Nachtzwaluw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('166',{naam:'Nonnetje',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('167',{naam:'Noordsekwikstaart',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('168',{naam:'Noordsenachtegaal',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('169',{naam:'Noordse pijlstormvogel',wetenschappelijke_naam:'Puffinus puffinus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('170',{naam:'Noordsestern',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('171',{naam:'Noordse stormvogel',wetenschappelijke_naam:'Fulmaris glacialis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('172',{naam:'Notenkraker',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('173',{naam:'Oehoe',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('174',{naam:'Oeverloper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('175',{naam:'Oeverpieper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('176',{naam:'Oeverzwaluw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('177',{naam:'Ooievaar',wetenschappelijke_naam:'Ciconia ciconia',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('178',{naam:'Orpheusspotvogel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('179',{naam:'Ortolaan',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('180',{naam:'Paapje',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('181',{naam:'Paarsestrandloper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('182',{naam:'Pallasboszanger',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('183',{naam:'Papegaaiduiker',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('184',{naam:'Parelduiker',wetenschappelijke_naam:'Gavia arctica',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('185',{naam:'Patrijs',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('186',{naam:'Pestvogel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('187',{naam:'Pijlstaart',wetenschappelijke_naam:'Anas acuta',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('188',{naam:'Pimpelmees',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('189',{naam:'Poelruiter',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('190',{naam:'Porseleinhoen',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('191',{naam:'Purperreiger',wetenschappelijke_naam:'Ardea purpurea',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('192',{naam:'Putter',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('193',{naam:'Ralreiger',wetenschappelijke_naam:'Ardeola ralloides',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('194',{naam:'Ransuil',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('195',{naam:'Regenwulp',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('196',{naam:'Reuzenstern',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('197',{naam:'Rietgors',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('198',{naam:'Rietzanger',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('199',{naam:'Ringmus',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('200',{naam:'Rodewouw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('201',{naam:'Roek',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('202',{naam:'Roerdomp',wetenschappelijke_naam:'Botaurus stellaris',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('203',{naam:'Roodborst',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('204',{naam:'Roodborsttapuit',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('205',{naam:'Roodhalsfuut',wetenschappelijke_naam:'Podiceps griseigena',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('206',{naam:'Roodhalsgans',wetenschappelijke_naam:'Branta ruficollis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('207',{naam:'Roodkeelduiker',wetenschappelijke_naam:'Gavia stellata',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('208',{naam:'Roodkeelpieper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('209',{naam:'Roodkopklauwier',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('210',{naam:'Roodmus',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('211',{naam:'Roodpootvalk',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('212',{naam:'Rossefranjepoot',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('213',{naam:'Rossegrutto',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('214',{naam:'Rotgans',wetenschappelijke_naam:'Branta bernicla',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('215',{naam:'Rouwkwikstaart',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('216',{naam:'Rozespreeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('217',{naam:'Ruigpootbuizerd',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('218',{naam:'Scharrelaar',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('219',{naam:'Scholekster',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('220',{naam:'Aalscholver1 mag weg',wetenschappelijke_naam:'Phalacrocorax carbo',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('221',{naam:'Siberischeboompieper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('222',{naam:'Sijs',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('223',{naam:'Slangenarend',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('224',{naam:'Slechtvalk',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('225',{naam:'Slobeend',wetenschappelijke_naam:'Spatula clypeata',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('226',{naam:'Smelleken',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('227',{naam:'Smient',wetenschappelijke_naam:'Anas penelope',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('228',{naam:'Sneeuwgans',wetenschappelijke_naam:'Anser caerulescens',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('229',{naam:'Sneeuwgors',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('230',{naam:'Sneeuwuil',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('231',{naam:'Snor',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('232',{naam:'Sperwer',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('233',{naam:'Sperwergrasmus',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('234',{naam:'Sperweruil',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('235',{naam:'Spotvogel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('236',{naam:'Spreeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('237',{naam:'Sprinkhaanzanger',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('238',{naam:'Staartmees',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('239',{naam:'Steenarend',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('240',{naam:'Steenloper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('241',{naam:'Steenuil',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('242',{naam:'Steltkluut',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('243',{naam:'Steppekievit',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('244',{naam:'Steppenkiekendief',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('245',{naam:'Stormmeeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('246',{naam:'Stormvogeltje',wetenschappelijke_naam:'Hydrobates pelagicus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('247',{naam:'Strandleeuwerik',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('248',{naam:'Strandplevier',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('249',{naam:'Tafeleend',wetenschappelijke_naam:'Aythya ferina',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('250',{naam:'Taigaboomkruiper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('251',{naam:'Taigarietgans',wetenschappelijke_naam:'Anser fabalis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('252',{naam:'Tapuit',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('253',{naam:'Temmincksstrandloper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('254',{naam:'Terekruiter',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('255',{naam:'Tjiftjaf',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('256',{naam:'Toendrarietgans',wetenschappelijke_naam:'Anser serrirostris',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('257',{naam:'Topper/Toppereend',wetenschappelijke_naam:'Aythya marila',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('258',{naam:'Torenvalk',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('259',{naam:'Tuinfluiter',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('260',{naam:'Tureluur',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('261',{naam:'Turksetortel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('262',{naam:'Vaal stormvogeltje',wetenschappelijke_naam:'Oceanodroma leucorhoa',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('263',{naam:'Valegier',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('264',{naam:'Valepijlstormvogel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('265',{naam:'Veldleeuwerik',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('266',{naam:'Velduil',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('267',{naam:'Vink',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('268',{naam:'Visdief',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('269',{naam:'Vorkstaartmeeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('270',{naam:'Vuurgoudhaan',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('271',{naam:'Waterhoen',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('272',{naam:'Waterpieper',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('273',{naam:'Waterral',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('274',{naam:'Waterrietzanger',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('275',{naam:'Watersnip',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('276',{naam:'Waterspreeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('277',{naam:'Wielewaal',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('278',{naam:'Wilde eend',wetenschappelijke_naam:'Anas platyrhynchos',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('279',{naam:'Wilde zwaan',wetenschappelijke_naam:'Cygnus cygnus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('280',{naam:'Winterkoning',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('281',{naam:'Wintertaling',wetenschappelijke_naam:'Anas crecca',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('282',{naam:'Witbandkruisbek',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('283',{naam:'Witgatje',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('284',{naam:'Withalsvliegenvanger',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('285',{naam:'Wittekwikstaart',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('286',{naam:'Witvleugelstern',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('287',{naam:'Witwangstern',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('288',{naam:'Woudaap',wetenschappelijke_naam:'Ixobrychus minutus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('289',{naam:'Wulp',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('290',{naam:'Zanglijster',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('291',{naam:'Zeearend',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('292',{naam:'Zeekoet',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('293',{naam:'Zilvermeeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('294',{naam:'Zilverplevier',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('295',{naam:'Zomertaling',wetenschappelijke_naam:'Anas querquedula',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('296',{naam:'Zomertortel',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('297',{naam:'Zwarte ibis',wetenschappelijke_naam:'Plegadis falcinellus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('298',{naam:'Zwartekraai',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('299',{naam:'Zwartemees',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('300',{naam:'Zwarte ooievaar',wetenschappelijke_naam:'Ciconia nigra',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('301',{naam:'Zwarteroodstaart',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('302',{naam:'Zwarteruiter',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('303',{naam:'Zwartespecht',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('304',{naam:'Zwartestern',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('305',{naam:'Zwartewouw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('306',{naam:'Zwarte zeeëend',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('307',{naam:'Zwartezeekoet',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('308',{naam:'Zwartkop',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('309',{naam:'Zwartkopmeeuw',wetenschappelijke_naam:'',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('310',{naam:'Elzenhaantje',wetenschappelijke_naam:'',type_organisme:'kever',afbeeldingen:[]})
organismenMap.set('311',{naam:'Geelsnavelduiker',wetenschappelijke_naam:'Gavia adamsii',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('312',{naam:'Bruin dikkopje',wetenschappelijke_naam:'Erynnis tages',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('313',{naam:'Oranjetipje',wetenschappelijke_naam:'Anthocharis cardamines',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('314',{naam:'Witgezoomd spikkeldikkopje',wetenschappelijke_naam:'Pyrgus carthami',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('315',{naam:'Voorjaarsspikkeldikkopje',wetenschappelijke_naam:'Pyrgus serratulae',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('316',{naam:'Rood spikkeldikkopje',wetenschappelijke_naam:'Pyrgus cirsii',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('317',{naam:'Bretons spikkeldikkopje',wetenschappelijke_naam:'Pyrgus armoricanus',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('318',{naam:'Groot spikkeldikkopje',wetenschappelijke_naam:'Pyrgus alveus',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('319',{naam:'Aardbeivlinder',wetenschappelijke_naam:'Pyrgus malvae',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('320',{naam:'Kalkgraslanddikkopje',wetenschappelijke_naam:'Spialia sertorius',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('321',{naam:'Kaasjeskruiddikkopje',wetenschappelijke_naam:'Carcharodus alcea',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('322',{naam:'Andoorndikkopje',wetenschappelijke_naam:'Carcharodus lavatherae',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('323',{naam:'Geelbont dikkopje',wetenschappelijke_naam:'Carterocephalus silvicolus',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('324',{naam:'Bont dikkopje',wetenschappelijke_naam:'Carterocephalus palaemon',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('325',{naam:'Spiegeldikkopje',wetenschappelijke_naam:'Heteropterus morpheus',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('326',{naam:'Kommavlinder',wetenschappelijke_naam:'Hesperia comma',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('327',{naam:'Groot dikkopje',wetenschappelijke_naam:'Ochlodes sylvanus',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('328',{naam:'Zwartsprietdikkopje',wetenschappelijke_naam:'Thymelicus lineola',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('329',{naam:'Geelsprietdikkopje',wetenschappelijke_naam:'Thymelicus sylvestris',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('330',{naam:'Dwergdikkopje',wetenschappelijke_naam:'Thymelicus acteon',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('331',{naam:'Zwarte apollovlinder',wetenschappelijke_naam:'Parnassius mnemosyne',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('332',{naam:'Apollovlinder',wetenschappelijke_naam:'Parnassius apollo',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('333',{naam:'Koningspage',wetenschappelijke_naam:'Iphiclides podalirius',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('334',{naam:'Koninginnepage',wetenschappelijke_naam:'Papilio machaon',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('335',{naam:'Boswitje',wetenschappelijke_naam:'Leptidae sinapis',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('336',{naam:'Verborgen boswitje',wetenschappelijke_naam:'Leptidea reali',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('337',{naam:'Groot geaderd witje',wetenschappelijke_naam:'Aporia crataegi',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('338',{naam:'Groot koolwitje',wetenschappelijke_naam:'Pieris brassicae',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('339',{naam:'Klein koolwitje',wetenschappelijke_naam:'Pieris rapae',type_organisme:'Dagvlinder',afbeeldingen:[]})
organismenMap.set('340',{naam:'Kuhls pijlstormvogel',wetenschappelijke_naam:'Calonectris diomedea',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('341',{naam:'Grote pijlstormvogel',wetenschappelijke_naam:'Puffinus gravis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('342',{naam:'Kleine pijlstormvogel',wetenschappelijke_naam:'Puffinus assimilis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('343',{naam:'Wilsons stormvogeltje',wetenschappelijke_naam:'Oceanites oceanicus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('344',{naam:'Witte pelikaan',wetenschappelijke_naam:'Pelecanus onocrotalus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('345',{naam:'Kroekoppelikaan',wetenschappelijke_naam:'Pelecanus crispus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('346',{naam:'Klein geaderd witje',wetenschappelijke_naam:'Pieris napi',type_organisme:'dagvlinder',afbeeldingen:[]})
organismenMap.set('347',{naam:'Resedawitje',wetenschappelijke_naam:'Pontia daplidice',type_organisme:'dagvlinder',afbeeldingen:[]})
organismenMap.set('348',{naam:'Oranje luzernevlinder',wetenschappelijke_naam:'Colias croceus',type_organisme:'dagvlinder',afbeeldingen:[]})
organismenMap.set('349',{naam:'Veengeeltje',wetenschappelijke_naam:'Colias palaeno',type_organisme:'dagvlinder',afbeeldingen:[]})
organismenMap.set('350',{naam:'Dwergaalscholver',wetenschappelijke_naam:'Microcarbo pygmaeus; Phalacrocorax pygmaeus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('351',{naam:'Amerikaanse roerdomp',wetenschappelijke_naam:'Botauris lentiginosus',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('352',{naam:'Rietgans',wetenschappelijke_naam:'Anser fabalis',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('353',{naam:'Blauwvleugeltaling',wetenschappelijke_naam:'Anas discors',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('354',{naam:'Siberische taling',wetenschappelijke_naam:'Anas formosa',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('355',{naam:'Amerikaanse smient',wetenschappelijke_naam:'Anas americana',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('356',{naam:'Marmereend',wetenschappelijke_naam:'Anas angustirostris',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('357',{naam:'Witoogeend',wetenschappelijke_naam:'Aythya nyroca',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('358',{naam:'Stellers eidereend',wetenschappelijke_naam:'Polysticta stelleri',type_organisme:'vogel',afbeeldingen:[]})
organismenMap.set('359',{naam:'Koningseider',wetenschappelijke_naam:'Somateria spectabilis',type_organisme:'vogel',afbeeldingen:[]})
MDZB_Object_Data.set('organismen',organismenMap);
